[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://script.google.com/macros/s/AKfycbw1CNlNVYhTSoGrEGZe9gN_B73riDFpXsKDYjzXXIrDhSyh7L2Rp6VlEdMllm2JDheTYw/exec"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript"
